### PR TITLE
Fixing issue #21.

### PR DESCRIPTION
**Pull request by lljrsr**
I hope this is according to your "style".

### CODE REVIEW

**Comment by lljrsr** [comment]
..I am not sure if this really fixes it.. I will have to try it out some more.

**Comment by sibiryakov** [comment]
This fix is overriding settings from ``distributed-frontera`` by ``frontera``, which is not what's needed. We need opposite behavior.

**Comment by lljrsr** [comment]
Thanks! I knew there was something wrong...
However my spider still does not seem to get any more pages to crawl after it crawled the initial seeds.

**Comment by sibiryakov** [comment]
Check here https://github.com/scrapinghub/distributed-frontera/pull/23

**Comment by lljrsr** [comment]
The DB workers still do not seem to communicate with the spiders any longer. My output looks like the following:
```
2015-12-18 16:28:05 Distributed Frontera ZeroMQ broker is started.
2015-12-18 16:28:05 {'sw_out_recvd': 0, 'db_out_recvd': 0, 'sw_in_recvd': 0, 'started': 1450456085.943339, 'spiders_in_recvd': 0, 'spiders_out_recvd': 0, 'db_in_recvd': 0}
2015-12-18 16:28:15 {'sw_out_recvd': 0, 'db_out_recvd': 0, 'sw_in_recvd': 0, 'started': 1450456085.943339, 'spiders_in_recvd': 0, 'spiders_out_recvd': 0, 'db_in_recvd': 2}
2015-12-18 16:28:25 {'sw_out_recvd': 0, 'db_out_recvd': 0, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 0, 'spiders_out_recvd': 0, 'db_in_recvd': 2}
2015-12-18 16:28:35 {'sw_out_recvd': 0, 'db_out_recvd': 0, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 0, 'db_in_recvd': 2}
2015-12-18 16:28:45 {'sw_out_recvd': 501, 'db_out_recvd': 0, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:28:55 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:05 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:15 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:25 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:35 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:46 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:29:56 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:06 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:16 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:26 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:36 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:46 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:30:56 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:06 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:16 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:26 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:36 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:46 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:31:56 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
2015-12-18 16:32:06 {'sw_out_recvd': 501, 'db_out_recvd': 46480, 'sw_in_recvd': 1, 'started': 1450456085.943339, 'spiders_in_recvd': 1, 'spiders_out_recvd': 502, 'db_in_recvd': 2}
```

**Comment by sibiryakov** [comment]
Please check with the latest master. My guess it's not related.

**Comment by lljrsr** [comment]
Awesome. Everything is working fine.
Again.. the error was also on my side.
And again.. thanks for your quick responses.

**Comment by sibiryakov** [comment]
Great!

**Pull request closed without merging**
